#------------------------------------------------------------
# Copyright (c) 2019 Thomas Kais
#
# This file is subject to the terms and conditions defined in
# file 'COPYING', which is part of this source code package.
#------------------------------------------------------------

# blacklist
branches:
  except:
    - gh-pages

matrix:
  include:
    - name: "macOS"
      os: osx
      osx_image: xcode10.2
      compiler: clang
      language: cpp
      before_install:
        - brew update
      install:
        #install latest Qt https://formulae.brew.sh/formula/qt and creates symlinks to installation
        - brew install qt
      before_script:
        - brew link --force qt
        - qmake -v
      script:
        - qmake -r
        - make -j2
      before_deploy:
        - macdeployqt FotoBox.app -dmg -verbose=2
        - mv -v ./FotoBox.dmg ./FotoBox_macOS.dmg

    - name: "Raspbian Stretch"
      os: linux
      dist: xenial
      language: ruby
      services:
        - docker
      before_install:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker build --tag buildfotobox --file DockerfileStretch .
      script:
        #execute 'CMD' command (Dockerfile)
        - docker run --volume $TRAVIS_BUILD_DIR:/artifact buildfotobox

    - name: "Raspbian Jessie"
      os: linux
      dist: xenial
      language: ruby
      services:
        - docker
      before_install:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker build --tag buildfotobox --file DockerfileJessie .
      script:
        #execute 'CMD' command (Dockerfile)
        - docker run --volume $TRAVIS_BUILD_DIR:/artifact buildfotobox

    - name: "Ubuntu Xenial CMake"
      os: linux
      dist: xenial
      language: cpp
      compiler: gcc
      sudo: false
      addons:
        apt:
          update: true
          packages:
            - qt5-default
            - qttools5-dev-tools
      before_script:
        - cmake --version
      script:
        - cmake CMakeLists.txt -G "Unix Makefiles"
        - make -j2
      before_deploy:
        - tar -cvzf ./FotoBox_Ubuntu_Xenial.tar.gz ./FotoBox

    - name: "Ubuntu Xenial Doxygen"
      os: linux
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - doxygen
            - graphviz
      before_script:
        - doxygen -v
      script:
        - doxygen Doxyfile
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: html
        github_token: $GH_REPO_TOKEN
        keep-history: true
        on:
          branch: develop

notifications:
  email: tomikais@t-online.de
  slack: foto-box:QXDcNQc86kOdnsSHinv0sqd6

deploy:
  provider: releases
  api_key: $GH_REPO_TOKEN
  file:
    - FotoBox_macOS.dmg
    - FotoBox_RasPi_jessie.tar.gz
    - FotoBox_RasPi_stretch.tar.gz
    - FotoBox_Ubuntu_Xenial.tar.gz
  skip_cleanup: true
  on:
    tags: true
