#------------------------------------------------------------
# Copyright (c) 2019 Thomas Kais
#
# This file is subject to the terms and conditions defined in
# file 'COPYING', which is part of this source code package.
#------------------------------------------------------------

# blacklist
branches:
  except:
    - gh-pages

matrix:
  include:
    - name: "macOS"
      os: osx
      osx_image: xcode10.2
      compiler: clang
      language: cpp
      before_install:
        - brew update
      install:
        #install latest Qt https://formulae.brew.sh/formula/qt and creates symlinks to installation
        - brew install qt
      before_script:
        - brew link --force qt
        - qmake -v
      script:
        - qmake -r
        - make -j2
      before_deploy:
        - macdeployqt FotoBox.app -dmg -verbose=2
        - mv -v ./FotoBox.dmg ./FotoBox_macOS.dmg

    - name: "Raspbian Stretch"
      os: linux
      dist: xenial
      language: ruby
      services:
        - docker
      before_install:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker build --tag buildfotobox --file resources/DockerfileStretch .
      script:
        #execute 'CMD' command (Dockerfile)
        - docker run --volume $TRAVIS_BUILD_DIR:/artifact buildfotobox

    - name: "Raspbian Jessie"
      os: linux
      dist: xenial
      language: ruby
      services:
        - docker
      before_install:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker build --tag buildfotobox --file resources/DockerfileJessie .
      script:
        #execute 'CMD' command (Dockerfile)
        - docker run --volume $TRAVIS_BUILD_DIR:/artifact buildfotobox

    - name: "Ubuntu Xenial CMake gcc"
      os: linux
      dist: xenial
      language: cpp
      compiler: gcc
      sudo: false
      addons:
        apt:
          update: true
          packages:
            - qt5-default
            - qttools5-dev-tools
      before_script:
        - cmake --version
        - gcc --version
      script:
        - cmake CMakeLists.txt -G "Unix Makefiles"
        - make -j2
      before_deploy:
        - tar -cvzf ./FotoBox_Ubuntu_Xenial.tar.gz ./FotoBox

    - name: "Ubuntu Xenial CMake Debug clang diagnostic 7"
      os: linux
      dist: xenial
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            # https://apt.llvm.org
            - llvm-toolchain-xenial-7
          update: true
          packages:
            - qt5-default
            - qttools5-dev-tools
            - clang-7
      env:
        - CC=clang-7
        - CXX=clang++-7
      script:
        # QtCreator -> Analyze -> clang -> Rule: "Clang ... almost everything" + -Wno-padded
        - cmake CMakeLists.txt -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-unused-macros -Wno-newline-eof -Wno-exit-time-destructors -Wno-global-constructors -Wno-gnu-zero-variadic-macro-arguments -Wno-documentation -Wno-shadow -Wno-switch-enum -Wno-missing-prototypes -Wno-used-but-marked-unused -Wno-padded"
        - make

    - name: "Ubuntu Xenial CMake Debug clang tidy 7"
      os: linux
      dist: xenial
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            # https://apt.llvm.org
            - llvm-toolchain-xenial-7
          update: true
          packages:
            - qt5-default
            - qttools5-dev-tools
            - llvm-7
            - clang-7
            - clang-tidy-7
      env:
        - CC=clang-7
        - CXX=clang++-7
        - CLANG_TIDY=clang-tidy-7
      script:
        - cmake CMakeLists.txt -G "Unix Makefiles" -DCMAKE_CXX_FLAGS="-Wno-everything" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_CLANG_TIDY=ON
        - make tidy

    - name: "macOS Doxygen"
      os: osx
      osx_image: xcode10.2
      before_install:
        - brew update
      install:
        - brew install doxygen graphviz
      before_script:
        - doxygen -v
      script:
        - doxygen resources/Doxyfile
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: html
        github_token: $GH_REPO_TOKEN
        keep-history: true
        on:
          branch: develop

notifications:
  email: tomikais@t-online.de
  slack: foto-box:QXDcNQc86kOdnsSHinv0sqd6

deploy:
  provider: releases
  api_key: $GH_REPO_TOKEN
  file:
    - FotoBox_macOS.dmg
    - FotoBox_RasPi_jessie.tar.gz
    - FotoBox_RasPi_stretch.tar.gz
    - FotoBox_Ubuntu_Xenial.tar.gz
  skip_cleanup: true
  on:
    tags: true
