matrix:
  include:
    - name: macOS
      os: osx
      compiler: clang
      language: cpp
      before_install:
        - brew update
      install:
        #install latest Qt https://formulae.brew.sh/formula/qt and creates symlinks to installation
        - brew install qt
        - brew link --force qt
      script:
        - qmake -v
        - qmake -r
        - make -j2
        - macdeployqt FotoBox.app -dmg -verbose=2
        - mv -v ./FotoBox.dmg ./FotoBox_macOS.dmg
    - name: Raspbian
      os: linux
      language: minimal
      dist: xenial
      sudo: true
      before_install:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker build --tag buildfotobox --file Dockerfile .
      script:
        #execute 'CMD' command (Dockerfile)
        - docker run --volume $TRAVIS_BUILD_DIR:/artifact buildfotobox

notifications:
  email: tomikais@t-online.de

deploy:
  provider: releases
  api_key:
    secure: VfkN32PaoMCfF+ceNC1MzLr+izDUCOIN2G0AKF2DDxQ08tJBfwIuQiR7UYfecqjzVoLD4IsOswPAh6J5wp3fNofzhqWagC5jJRdgWo435cwPHkdbm39WN+j1LMhJn2Uwr51HBQp9FkTWQBPS6JPnKFhG2iuDDIBxx9am24sg3N/tHRAAhgscrlibenxRaEK47aRny+V0fArc9O6tFEPL+bQQlq+P1brV6FJaRjjYp0k3TZtJDW/CWiQEbTOeB4BykDrro5AkRic73M+VizzX4ojy1cB7wArLoqV2+mawiQ3HKIL6DSK5z+XZb9kQk8JPtr/MUJcKcZOvAT4PnspZbcFWfC/3zwigXM2lV6tNcfC5qLxHGjV2ryHi2omEtb9cozaZdG/X0SVKdV9YRI21tONYHIFK8d9fDunB91mI+7SyCHo5T4TKXfD1P7ynB13MYtY2kKkv9TzYqaQBwlhp9XChQpjzqJOmPVIpBYou3QYvwpi2Dzis8TdWjxHAmeJ1c4jMq4T0gKNuodPh4fd4YJVY+lCr37DnHWlKELRmFhfnAZfpU4uE6nSYNaznZgC4YvEte1Ju8wvndBVnA6q3bs0rNqQ05+9Jre9QgpeLT9GUPMVIlEO4tLrE90x2B96MiHCOHwhaHqXvZfRc4ws1XVV2J9ywYZzmsnXCfASrKmQ=
  file:
    - FotoBox_macOS.dmg
    - FotoBox_RasPi.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: tomikais/fotobox
